# Generated by Django 5.0.6 on 2024-07-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadp_about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/'),
        ),
    ]
