# Generated by Django 5.0.6 on 2024-07-05 06:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadp_about', '0002_alter_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
