# Generated by Django 5.0.6 on 2024-07-05 06:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadp_content', '0002_alter_news_options_achievement_image_news_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
