# Generated by Django 5.0.6 on 2024-07-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadp_content', '0003_achievement_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='language_code',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='en', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='language_code',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='en', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='language_code',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='en', max_length=2),
            preserve_default=False,
        ),
    ]
