# Generated by Django 5.0.6 on 2024-07-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadp_content', '0004_achievement_language_code_news_language_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='news',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='language_code',
        ),
    ]
