# Generated by Django 5.0.6 on 2024-07-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='reports_images/')),
                ('file', models.FileField(upload_to='reports_files/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('grant_type', models.CharField(choices=[('local', 'Local'), ('international', 'International')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='reports_images/')),
                ('file', models.FileField(upload_to='reports_files/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
