# Generated by Django 5.0.6 on 2024-07-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadp_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
