# Generated by Django 5.0.6 on 2024-07-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadp_polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='options',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='participants_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='questions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], default='single_choice', max_length=20),
        ),
    ]
