# Generated by Django 5.0.6 on 2024-07-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadp_contact', '0002_alter_contact_latitude_alter_contact_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
